Repository SKHUAZ/SKHUAZ, pull requests merged in 2023-10, with the labels that each got.

#42 [Fix] #33 - 영상 촬영까지 자잘한 버그들을 Fix합니다
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Network/API/Evaluates/EvaluateAPI.swift
  SKHUAZ/SKHUAZ/Network/DTO/Evaluate/DelEvaluateDTO.swift
  SKHUAZ/SKHUAZ/Network/Router/EvaluateRouter/EvaluateRouter.swift
  SKHUAZ/SKHUAZ/Presentation/Essential/View/EssentialView.swift
  SKHUAZ/SKHUAZ/Presentation/Essential/ViewController/EssentialViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Essential/ViewController/TutorialEssentialViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/View/EvaluateView.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/DetailEvaluateViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/EvaluateViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Home/ViewController/HomeViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Login/ViewController/LoginViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/RecommendTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/CreateRecommendVC.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/RecommendVC.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/View/SignUpView.swift
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/QuestionMark.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/QuestionMark.imageset/QuestionMark.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/QuestionMark.imageset/QuestionMark@2x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/QuestionMark.imageset/QuestionMark@3x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/data.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/data.imageset/_data.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/data.imageset/_data@2x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/data.imageset/_data@3x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/java.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/java.imageset/java.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/java.imageset/java@2x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/java.imageset/java@3x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/leftVector.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/leftVector.imageset/leftVector.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/leftVector.imageset/leftVector@2x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/leftVector.imageset/leftVector@3x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/python.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/python.imageset/python.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/python.imageset/python@2x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/python.imageset/python@3x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/rightVector.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/rightVector.imageset/rightVector.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/rightVector.imageset/rightVector@2x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/rightVector.imageset/rightVector@3x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/web.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/web.imageset/_web.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/web.imageset/_web@2x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/web.imageset/_web@3x.png
  SKHUAZ/SKHUAZ/Util/NameSpace/Image.swift
Labels: 🌱 Feat, 🦭 성우

#46 [Feature] #44 - 미완성 기능 및 요소 추가 구현
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Network/DTO/Evaluate/DelEvaluateDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/User/EditProfileDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/User/SignUpResponseDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/User/emailAuthDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/User/logInDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/User/logOutDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/User/nicknameCheckDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/User/signOutDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/emailAuthDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/logOutDTO.swift
  SKHUAZ/SKHUAZ/Network/Foundation/BaseAPI.swift
  SKHUAZ/SKHUAZ/Network/Foundation/BaseResponse.swift
  SKHUAZ/SKHUAZ/Network/Foundation/NetworkResult.swift
  SKHUAZ/SKHUAZ/Network/Router/UserRouter/UserRouter.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/CreateEvaluateBottomSheetViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Setting/ViewController/SettingViewController.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/View/SignUpView.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/ViewController/CreateEmailAuthViewController.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/ViewController/SignUpViewController.swift
  SKHUAZ/SKHUAZ/Util/CustomClass/AlertViewController.swift
Labels: 🎈 Fix, 🎀 Add, 🌱 Feat, 🕷️ 인호

#50 [Feature] #45 - 미완성 기능 및 요소 추가 구현
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Network/API/RootRecommend/RootRecommendAPI.swift
  SKHUAZ/SKHUAZ/Network/API/preLecture/preLectureAPI.swift
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/AllRootRecommendResponseDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/CreateRootRecommendDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/DetailRootRecommendDTO.swift
  SKHUAZ/SKHUAZ/Network/Router/RootRecommendRouter/RootRecommendRouter.swift
  SKHUAZ/SKHUAZ/Network/Router/preLecture/preLectureRouter.swift
  SKHUAZ/SKHUAZ/Presentation/Home/ViewController/HomeViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/DataModel/RecommendDataModel.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/DataModel/RootRecommendDataModel.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/CreateRecommendView.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/importRootTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/CreateRecommendVC.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/DetailRecommendViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/RecommendVC.swift
Labels: 🎈 Fix, 🌱 Feat, 🐳 신영

#53 [Feature] #52 - 루트추천 보완
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Network/API/RootRecommend/RootRecommendAPI.swift
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/AllRootRecommendResponseDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/CreateRecommendRequestBody.swift
  SKHUAZ/SKHUAZ/Network/Router/RootRecommendRouter/RootRecommendRouter.swift
  SKHUAZ/SKHUAZ/Presentation/Home/ViewController/HomeViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/DataModel/RootRecommendDataModel.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/CreateRecommendView.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/importRootTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/CreateRecommendBottomSheetViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/CreateRecommendVC.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/DetailRecommendViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/RecommendVC.swift
Labels: 🌱 Feat, 🐳 신영

#54 [Fix] #51 - 시연 이전 코드 수정
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Network/API/Evaluates/EvaluateAPI.swift
  SKHUAZ/SKHUAZ/Network/DTO/Evaluate/MyEvaluationsDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/preLecture/preLectureDTO.swift
  SKHUAZ/SKHUAZ/Network/Router/EvaluateRouter/EvaluateRouter.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/View/ColorNotifyView.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/View/EvaluateView.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/DetailEvaluateViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/EvaluateViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Home/ViewController/HomeViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/RecommendTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/importRootTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/CreateRecommendVC.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/RecommendVC.swift
Labels: 🎈 Fix, 🦭 성우

#57 [Feature] #56 - 코드보완
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Network/API/RootRecommend/RootRecommendAPI.swift
  SKHUAZ/SKHUAZ/Network/DTO/Home/HomeDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/DelRecommendDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/EditRootRecommendDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/EditRootRecommendRequestBody.swift
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/MyRecommendsDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/preLecture/preLectureDTO.swift
  SKHUAZ/SKHUAZ/Network/Router/RootRecommendRouter/RootRecommendRouter.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/View/EvaluateTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/EvaluateViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Home/ViewController/HomeViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/CreateRecommendView.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/DetailTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/RecommendTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/importRootTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/CreateRecommendBottomSheetViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/CreateRecommendVC.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/DetailRecommendViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/RecommendVC.swift
Labels: 🎈 Fix, 🍄 Del, 🌱 Feat, 🐳 신영

#58 [Fix] #55 - Complementing features & code Fix
  SKHUAZ/SKHUAZ/Presentation/Essential/View/EssentialView.swift
  SKHUAZ/SKHUAZ/Presentation/Essential/ViewController/EssentialViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/View/ColorNotifyView.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/EvaluateViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Home/ViewController/HomeViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/DetailTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/RecommendTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Setting/View/EditProfileView.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/View/SignUpView.swift
  SKHUAZ/SKHUAZ/Util/CustomClass/AlertViewController.swift
  SKHUAZ/SKHUAZ/Util/CustomClass/RadioButtonsStack.swift
Labels: 🎈 Fix, 🦭 성우

#63 [Fix] #62 - code Fix
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/AllRootRecommendResponseDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/DetailRootRecommendDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/MyRecommendsDTO.swift
  SKHUAZ/SKHUAZ/Presentation/Home/ViewController/HomeViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/DataModel/RootRecommendDataModel.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/RecommendTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/DetailRecommendViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/RecommendVC.swift
Labels: 🎈 Fix, 🐳 신영

#64 [Fix] #61 - Complementing features & code Fix
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/DetailEvaluateViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Home/ViewController/HomeViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Setting/View/EditProfileView.swift
  SKHUAZ/SKHUAZ/Presentation/Setting/ViewController/EditProfileViewController.swift
Labels: 🎈 Fix, 🌱 Feat, 🦭 성우

#67 [Fix] #66 - Fix
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/DetailRootRecommendDTO.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/AlertViewOfRecommendController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/CreateRecommendVC.swift
Labels: 🎈 Fix, 🎀 Add, 🐳 신영

#68 [Fix] #65 - Last Fix
  SKHUAZ/SKHUAZ/Presentation/Essential/ViewController/EssentialViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Essential/ViewController/SaveEssentialViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Home/ViewController/HomeViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Login/View/LoginView.swift
  SKHUAZ/SKHUAZ/Presentation/Login/ViewController/LoginViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Setting/ViewController/SettingViewController.swift
Labels: 🎈 Fix, 🦭 성우
