Repository SKHUAZ/SKHUAZ, pull requests merged in 2023-09, with the labels that each got.

#6 [Feature] #3 - 로그인 View를 구현합니다
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Presentation/Login/View/LoginView.swift
  SKHUAZ/SKHUAZ/Presentation/Login/ViewController/LoginViewController.swift
  SKHUAZ/SKHUAZ/Util/StyleGuide/CustomColor.swift
Labels: 🌱 Feat, 🕷️ 인호

#9 [Feature] #4 - 강의평 화면을 구현합니다
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Application/SceneDelegate.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/DataModel/EvaluateDataModel.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/View/CreateEvaluateView.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/View/DetailEvaluateView.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/View/EvaluateCircleChart.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/View/EvaluateTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/CreateEvaluateViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/EvaluateViewController.swift
  SKHUAZ/SKHUAZ/Presentation/TabBar/View/TabBarItem.swift
  SKHUAZ/SKHUAZ/Presentation/TabBar/ViewController/TabBarViewController.swift
  SKHUAZ/SKHUAZ/Presentation/TabBar/ViewController/TabBatViewController.swift
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/CreateButton.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/CreateButton.imageset/CreateButton.svg
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/WritingOff.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/WritingOff.imageset/WritingOff.svg
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/WritingOn.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/WritingOn.imageset/WritingOn.svg
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/logo/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/logo/SKHUAZ*1.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/logo/SKHUAZ*1.imageset/SKHUAZ*1.svg
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/logo/SKHUAZ*3.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/logo/SKHUAZ*3.imageset/SKHUAZ*3.svg
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/logo/SKHUAZ.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/logo/SKHUAZ.imageset/SKHUAZ.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/logo/SKHUAZ.imageset/SKHUAZ@2x.png
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/logo/SKHUAZ.imageset/SKHUAZ@3x.png
  SKHUAZ/SKHUAZ/Util/CustomClass/CircleGraph.swift
  SKHUAZ/SKHUAZ/Util/CustomClass/EvaluateMenu.swift
  SKHUAZ/SKHUAZ/Util/CustomClass/EvaluateTextFieldView.swift
  SKHUAZ/SKHUAZ/Util/CustomClass/UILabelPadding.swift
  SKHUAZ/SKHUAZ/Util/Extension/UIResponder++.swift
  SKHUAZ/SKHUAZ/Util/Extension/UIStackView++.swift
  SKHUAZ/SKHUAZ/Util/Extension/UITextField++.swift
  SKHUAZ/SKHUAZ/Util/Extension/UIViewController++.swift
  SKHUAZ/SKHUAZ/Util/NameSpace/Color.swift
  SKHUAZ/SKHUAZ/Util/NameSpace/Image.swift
Labels: 🌱 Feat, 🦭 성우

#11 [Feature] #5 - 루트추천 뷰를 구현합니다
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SKHUAZ/SKHUAZ/Presentation/Base/View/BaseView.swift
  SKHUAZ/SKHUAZ/Presentation/Base/ViewController/TestViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/DataModel/RecommendDM.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/DataModel/RecommendDataModel.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/CreateRecommendAfterBringView.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/CreateRecommendTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/CreateRecommendView.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/RecommendTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/CreateRecommendVC.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/RecommendVC.swift
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Assets.xcassets/Image.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/Search.imageset/Contents.json
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/Search.imageset/Search.svg
Labels: 🌱 Feat

#15 [Feature] #8 - 회원가입 뷰 구현을 완료합니다.
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Application/SceneDelegate.swift
  SKHUAZ/SKHUAZ/Presentation/Login/View/LoginView.swift
  SKHUAZ/SKHUAZ/Presentation/Login/ViewController/LoginViewController.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/View/SignUpView.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/ViewController/SignUpViewController.swift
  SKHUAZ/SKHUAZ/Util/CustomClass/RadioButton.swift
  SKHUAZ/SKHUAZ/Util/CustomClass/RadioButtonsStack.swift
  SKHUAZ/SKHUAZ/Util/Extension/UIStackView++.swift
Labels: 🌱 Feat, 🕷️ 인호

#21 [Feat] #20 SignUpView 구현 완료
  SKHUAZ/SKHUAZ.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SKHUAZ/SKHUAZ/Application/SceneDelegate.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/View/SignUpView.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/ViewController/SignUpViewController.swift
Labels: 🎈 Fix, 🌱 Feat

#27 [Fix] #24 - 🔥🔥🔥🔥Hot Fix🔥🔥🔥🔥
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Presentation/Recommend/DataModel/ImportRootModel.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/DataModel/RecommendDataModel.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/CreateRecommendAfterBringView.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/CreateRecommendTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/CreateRecommendView.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/RecommendTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/importRootTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/AlertViewOfRecommendController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/CreateRecommendBottomSheetViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/CreateRecommendVC.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/DetailRecommendViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/RecommendVC.swift
  SKHUAZ/SKHUAZ/Util/CustomClass/CustomRootContainer.swift
Labels: 🎈 Fix, 🍑 Merge, 🦭 성우

#28 [Feature] #18 - Alamofire 서버통신을 셋팅합니다
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Application/Info.plist
  SKHUAZ/SKHUAZ/Application/SceneDelegate.swift
  SKHUAZ/SKHUAZ/Data/Model/Model.swift
  SKHUAZ/SKHUAZ/Network/API/Evaluates/EvaluateAPI.swift
  SKHUAZ/SKHUAZ/Network/APIService/APIService.swift
  SKHUAZ/SKHUAZ/Network/Config/Config.swift
  SKHUAZ/SKHUAZ/Network/DTO/AllevaluateResponseDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/DTO.swift
  SKHUAZ/SKHUAZ/Network/Foundation/APIConst.swift
  SKHUAZ/SKHUAZ/Network/Foundation/AlamofireLogger.swift
  SKHUAZ/SKHUAZ/Network/Foundation/BaseAPI.swift
  SKHUAZ/SKHUAZ/Network/Foundation/BaseResponse.swift
  SKHUAZ/SKHUAZ/Network/Foundation/BaseTargetType.swift
  SKHUAZ/SKHUAZ/Network/Foundation/GeneralResponse.swift
  SKHUAZ/SKHUAZ/Network/Foundation/NetworkResult.swift
  SKHUAZ/SKHUAZ/Network/Foundation/URLConst.swift
  SKHUAZ/SKHUAZ/Network/Router/EvaluateRouter/EvaluateRouter.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/DataModel/EvaluateDataModel.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/View/EvaluateTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/EvaluateViewController.swift
Labels: 🌱 Feat, 🦭 성우

#30 [Feature] #26 - LoginView 수정 및 API 연결 완료
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Application/SceneDelegate.swift
  SKHUAZ/SKHUAZ/Network/API/User/UserAPI.swift
  SKHUAZ/SKHUAZ/Network/DTO/EditProfileDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/SignUpResponseDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/emailAuthDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/logInDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/logOutDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/nicknameCheckDTO.swift
  SKHUAZ/SKHUAZ/Network/Foundation/NetworkResult.swift
  SKHUAZ/SKHUAZ/Network/Router/EvaluateRouter/EvaluateRouter.swift
  SKHUAZ/SKHUAZ/Network/Router/UserRouter/UserRouter.swift
  SKHUAZ/SKHUAZ/Presentation/Login/View/LoginView.swift
  SKHUAZ/SKHUAZ/Presentation/Login/ViewController/LoginViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Setting/View/EditProfileView.swift
  SKHUAZ/SKHUAZ/Presentation/Setting/View/SettingView.swift
  SKHUAZ/SKHUAZ/Presentation/Setting/ViewController/SettingViewController.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/View/SignUpView.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/ViewController/CreateEmailAuthViewController.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/ViewController/SignUpViewController.swift
Labels: 🎈 Fix, 🌱 Feat, 🕷️ 인호

#32 [Feature] #29 - 선수과목제도 제출 UI 구현합니다
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Network/API/Evaluates/EvaluateAPI.swift
  SKHUAZ/SKHUAZ/Network/API/Lecture/LectureAPI.swift
  SKHUAZ/SKHUAZ/Network/API/preLecture/preLectureAPI.swift
  SKHUAZ/SKHUAZ/Network/DTO/Evaluate/AllevaluateResponseDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/Evaluate/CreateEvaluateDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/Evaluate/CreateEvaluateRequestBody.swift
  SKHUAZ/SKHUAZ/Network/DTO/Evaluate/DetailEvaluateDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/Lecture/AllLectureDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/Lecture/AllLectureRequestBody.swift
  SKHUAZ/SKHUAZ/Network/DTO/Lecture/AllProfessorDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/Lecture/AllProfessorRequestBody.swift
  SKHUAZ/SKHUAZ/Network/DTO/Lecture/SemestersDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/preLecture/PreLectureRequestBodyElement.swift
  SKHUAZ/SKHUAZ/Network/DTO/preLecture/preLectureDTO.swift
  SKHUAZ/SKHUAZ/Network/Foundation/BaseTargetType.swift
  SKHUAZ/SKHUAZ/Network/Router/EvaluateRouter/EvaluateRouter.swift
  SKHUAZ/SKHUAZ/Network/Router/LectureRouter/LectureRouter.swift
  SKHUAZ/SKHUAZ/Network/Router/preLecture/preLectureRouter.swift
  SKHUAZ/SKHUAZ/Presentation/Essential/DataModel/EssentialDataModel.swift
  SKHUAZ/SKHUAZ/Presentation/Essential/View/EssentialView.swift
  SKHUAZ/SKHUAZ/Presentation/Essential/ViewController/EssentialBottomSheetViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Essential/ViewController/EssentialViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Essential/ViewController/SaveEssentialViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/AlertViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/CreateEvaluateBottomSheetViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/CreateEvaluateViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/DetailEvaluateViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Evaluate/ViewController/EvaluateViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Login/ViewController/LoginViewController.swift
  SKHUAZ/SKHUAZ/Util/CustomClass/AlertViewController.swift
  SKHUAZ/SKHUAZ/Util/CustomClass/LectureButton.swift
  SKHUAZ/SKHUAZ/Util/CustomClass/SaveEssentialContainerView.swift
  SKHUAZ/SKHUAZ/Util/CustomClass/SaveEssentialSubContainerView.swift
  SKHUAZ/SKHUAZ/Util/NameSpace/Literals.swift
Labels: 🌱 Feat, 🦭 성우

#37 [Fix] #31 - 버그 수정
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Network/API/User/UserAPI.swift
  SKHUAZ/SKHUAZ/Network/DTO/SignUpResponseDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/signOutDTO.swift
  SKHUAZ/SKHUAZ/Network/Router/UserRouter/UserRouter.swift
  SKHUAZ/SKHUAZ/Presentation/Login/View/LoginView.swift
  SKHUAZ/SKHUAZ/Presentation/Login/ViewController/LoginViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Setting/ViewController/EditProfileViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Setting/ViewController/SettingViewController.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/View/SignUpView.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/ViewController/CreateEmailAuthViewController.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/ViewController/SignUpViewController.swift
Labels: 🎈 Fix, 🕷️ 인호

#40 [Feat] #39 - Add SignView nicknamecheck Logic
  SKHUAZ/SKHUAZ/Network/DTO/nicknameCheckDTO.swift
  SKHUAZ/SKHUAZ/Network/Foundation/NetworkResult.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/View/SignUpView.swift
  SKHUAZ/SKHUAZ/Presentation/SignUp/ViewController/SignUpViewController.swift
Labels: 🌱 Feat, 🕷️ 인호

#41 Feature/#38
  SKHUAZ/SKHUAZ.xcodeproj/project.pbxproj
  SKHUAZ/SKHUAZ/Network/API/RootRecommend/RootRecommendAPI.swift
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/AllRootRecommendResponseDTO.swift
  SKHUAZ/SKHUAZ/Network/DTO/RootRecommend/CreateRootRecommendDTO.swift
  SKHUAZ/SKHUAZ/Network/Router/RootRecommendRouter/RootRecommendRouter.swift
  SKHUAZ/SKHUAZ/Presentation/Home/ViewController/HomeViewController.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/DataModel/RecommendDataModel.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/DataModel/RootRecommendDataModel.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/RecommendTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/View/importRootTableViewCell.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/CreateRecommendVC.swift
  SKHUAZ/SKHUAZ/Presentation/Recommend/ViewController/RecommendVC.swift
  SKHUAZ/SKHUAZ/Presentation/TabBar/TabBarViewController.swift
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/BringRootRecommend.imageset/BringRootRecommend.svg
  SKHUAZ/SKHUAZ/Resource/AsseCatalog/Image.xcassets/BringRootRecommend.imageset/Contents.json
  SKHUAZ/SKHUAZ/Util/NameSpace/Image.swift
Labels: 🎈 Fix, 🌱 Feat, 🍑 Merge, 🐳 신영
